[project]
name = "devpy"
version = "0.1a3.dev0"
requires-python = ">=3.7"
description = "Developer tool for scientific Python libraries"
license = {file = "LICENSE"}
maintainers = [
  {name = "Scientific Python", email = "devpy@discuss.scientific-python.org"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
dependencies = [
  "click",
  "toml",
  "colorama; platform_system == 'Windows'"
]

[project.optional-dependencies]
lint = ["pre-commit >= 2.20"]

[project.urls]
homepage = "https://github.com/scientific-python/devpy"

[tool.setuptools.packages.find]
include = ["devpy*"]
