name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.11

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test_devpy:
    strategy:
      matrix:
        python_version: ['3.7', '3.11']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install
        run: |
          pip install -e .
          pip install pytest meson-python ninja
      - name: Test
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        env:
          TERM: xterm-256color
        run: |
          cd example_pkg
          ./dev.py build
          ./dev.py test
